export const data = [
    {
      name: "Viola Amherd",
      date: "19/11/2023",
      id: "123456789",
      post: "Administracion",
      MC: "Preempleo",
      status: "activo",
    },
    {
      name: "Simonetta Sommaruga",
      date: "19/11/2023",
      id: "123456789",
      MC: "Preempleo",
      post: "Administracion",
      status: "activo",
    },
    {
      name: "Alain Berset",
      date: "19/11/2023",
      id: "123456789",
      MC: "Preempleo",
      post: "Estudiante",
      status: "activo",
    },
    {
      name: "Ignazio Cassis",
      date: "19/11/2023",
      id: "123456789",
      post: "Administracion",
      MC: "Preempleo",
      status: "activo",
    },
    {
      name: "Karin Keller-Sutter",
      date: "19/11/2023",
      id: "123456789",
      MC: "Preempleo",
      post: "Estudiante",
      status: "activo",
    },
    {
      name: "Guy Parmelin",
      date: "19/11/2023",
      id: "123456789",
      MC: "Preempleo",
      post: "Administracion",
      status: "activo",
    },
    {
      name: "Elisabeth Baume-Schneider",
      date: "19/11/2023",
      id: "123456789",
      MC: "Preempleo",
      post: "Estudiante",
      status: "activo",
    },
  ];