export const data = [
  {
    name: "Carlos Gómez",
    date: "05/01/2024",
    id: "27654321",
    post: "Administracion",
    MC: "Evaluación Anual",
    status: "inactivo",
  },
  {
    name: "Mariana Fuentes",
    date: "12/01/2024",
    id: "29876543",
    post: "Administracion",
    MC: "Ingreso",
    status: "activo",
  },
  {
    name: "José Martínez",
    date: "19/01/2024",
    id: "24567890",
    post: "Estudiante",
    MC: "Revisión Médica",
    status: "activo",
  },
  {
    name: "Luisa Castillo",
    date: "26/01/2024",
    id: "26789012",
    post: "Administración",
    MC: "Capacitación",
    status: "inactivo",
  },
  {
    name: "Gabriela Ramírez",
    date: "02/02/2024",
    id: "28901234",
    post: "Estudiante",
    MC: "Evaluación Psicológica",
    status: "activo",
  },
  {
    name: "Andrés Pérez",
    date: "09/02/2024",
    id: "21034567",
    post: "Administración",
    MC: "Actualización de Datos",
    status: "inactivo",
  },
  {
    name: "Sofía Morales",
    date: "16/02/2024",
    id: "22345678",
    post: "Estudiante",
    MC: "Consulta General",
    status: "activo",
  },
  {
    name: "Eduardo Villa",
    date: "07/01/2024",
    id: "39567890",
    post: "Administración",
    MC: "Inducción de Personal",
    status: "activo",
  },
  {
    name: "Samantha Colmenares",
    date: "15/01/2024",
    id: "40789123",
    post: "Administración",
    MC: "Formación en Gestión",
    status: "inactivo",
  },
  {
    name: "Diego Rangel",
    date: "23/01/2024",
    id: "41901234",
    post: "Estudiante",
    MC: "Orientación Académica",
    status: "activo",
  },
  {
    name: "Lucía Méndez",
    date: "31/01/2024",
    id: "43012345",
    post: "Administración",
    MC: "Desarrollo Profesional",
    status: "inactivo",
  },
  {
    name: "Omar González",
    date: "08/02/2024",
    id: "44234567",
    post: "Estudiante",
    MC: "Asesoría de Carrera",
    status: "activo",
  },
  {
    name: "Carmen Lugo",
    date: "16/02/2024",
    id: "45345678",
    post: "Administración",
    MC: "Evaluación de Competencias",
    status: "inactivo",
  },
  {
    name: "Julio César Salas",
    date: "24/02/2024",
    id: "46456789",
    post: "Estudiante",
    MC: "Revisión de Plan de Estudios",
    status: "activo",
  },
];
